set nocompatible

set modeline

set nobackup
set nowritebackup
set noswapfile
set hidden
set ttyfast

set noexpandtab
set tabstop=8
set softtabstop=8
set shiftwidth=8

set number "relativenumber
set ruler nowrap
set foldcolumn=1
set hlsearch incsearch showmatch
set noshowmode

set autoindent
set cinoptions=:0,t0,+4,(4
set backspace=eol,start,indent
set whichwrap=b,s,<,>,[,]
set comments=s1:/*,mb:*,ex:*/
set foldenable

" reload file when changed externally
set autoread

set wildmenu
set wildmode=full
set wildignore+=*/.git/*,*/.hg/*,*/.svn/*,*/.DS_Store

" status bar
set laststatus=2
set statusline=\[%n]
set statusline+=\ %F
set statusline+=\ %m
set statusline+=%y[%{&ff}]%{HasPaste()}
set statusline+=%=
" currentline : totallines : linepercent : column
set statusline+=\ [\ %v:%l:%L:%p%%
set statusline+=\ ]

syntax on
filetype plugin on
filetype indent on

set encoding=utf8
set fileformats=unix,dos,mac

augroup C
	autocmd!
	autocmd BufNewFile,BufRead {*.c,*.h,*.cpp} setlocal cindent
	autocmd BufNewFile,BufRead {*.c,*.h,*.cpp} setlocal tabstop=8 softtabstop=8 shiftwidth=8 noexpandtab
augroup END

augroup Groff
	autocmd!
	autocmd BufNewFile,BufRead *.groff,*.[1-9] setlocal filetype=groff
augroup END

augroup SQL
	autocmd!
	autocmd BufNewFile,BufRead *.sql,*.mysql setlocal filetype=mysql
	autocmd BufNewFile,BufRead *.pgsql setlocal filetype=pgsql
augroup END

augroup JSON
	autocmd!
	autocmd BufNewFile,BufRead *.json setlocal tabstop=2 softtabstop=2 shiftwidth=2 expandtab
augroup END

colorscheme delek
set background=dark
set t_Co=256

set list listchars=tab:\ .
highlight SpecialKey ctermfg=DarkRed
set list!

highlight ExtraWhitespace ctermbg=red
match ExtraWhitespace /\s\+$/

highlight Folded ctermbg=black ctermfg=grey

let mapleader = "-"

nnoremap <leader>c :noh<cr>
nnoremap <leader>l :set list!<cr>
nnoremap <leader>p :setlocal paste!<cr>
nnoremap <leader>4 :setlocal tabstop=4 softtabstop=4 shiftwidth=4<cr>
nnoremap <leader>8 :setlocal tabstop=8 softtabstop=8 shiftwidth=8<cr>

function! HasPaste()
	if &paste
		return '[paste]'
	endif
	return ''
endfunction

" https://github.com/vim-airline/vim-airline
" https://github.com/vim-airline/vim-airline-themes
let g:airline_theme = 'molokai'
let g:airline#extensions#tabline#enabled = 1

" https://github.com/w0rp/ale
let g:ale_sign_column_always = 1
let g:ale_lint_on_text_changed = 'normal'
let g:ale_lint_on_insert_leave = 1
