[theme]
theme = "slick"

[icons]
icons = "awesome6"

[[block]]
block = "net"
device = "wlan0"
interval = 5
format = " wlan0: $ip"

[[block]]
block = "cpu"
interval = 1

[[block]]
block = "memory"
format = " $icon $mem_total_used_percents"

[[block]]
block = "disk_space"
path = "/"
info_type = "used"
alert_unit = "GB"
warning = 13.0
alert = 14.0
format = " $icon $available/$total ($percentage)"

[[block]]
block = "battery"
interval = 10
format = " $icon $percentage $time"

[[block]]
block = "time"
interval = 60
format = " $icon $timestamp.datetime(f:'%a %Y-%m-%d %R')"
