theme = "slick"
icons = "awesome"

[[block]]
block = "net"
device = "wlp4s0"
interval = 5
format = "wlp4s0: {ip}"

[[block]]
block = "cpu"
interval = 1

[[block]]
block = "memory"
display_type = "memory"
format_mem = "{mem_total_used_percents} {mem_total_used}/{mem_total}"
clickable = false

[[block]]
block = "sound"

[[block]]
block = "battery"
interval = 10
format = "{percentage} {time}"

[[block]]
block = "time"
interval = 60
format = "%a %Y-%m-%d %R"
