theme = "slick"
icons = "awesome"

[[block]]
block = "net"
device = "enp5s0"
ip = true
speed_up = false
speed_down = false
graph_up = false
graph_down = false
interval = 5

[[block]]
block = "cpu"
interval = 1

[[block]]
block = "memory"
display_type = "memory"
format_mem = "{Mup}%"
format_swap = "{SUp}%"

[[block]]
block = "load"
interval = 1
format = "{1m}"

[[block]]
block = "sound"

[[block]]
block = "time"
interval = 60
format = "%a %Y-%m-%d %R"
