#!/usr/bin/env bash
OS=`uname -s`
case "$OS" in
	FreeBSD|DragonFly)	ETC=/usr/local/etc;;
	*)			ETC=/etc;;
esac
RCFILE=$ETC/bash.colvin

set -e

unset PRIMARY_INSTALLED

function install_primary() {
	if [ -z "$PRIMARY_INSTALLED" ]
	then
		install -o root -g wheel -m 664 bash.colvin "$RCFILE"
		PRIMARY_INSTALLED=1
	fi
}

function install_user() {
	user="$1"
	case "$1" in
		root)	homedir="/root";;
		*)	homedir="/home/$user";;
	esac
	install_primary
	cat << EOF | tee $homedir/.bashrc $homedir/.bash_profile 1>/dev/null
[[ -z "\$colvinrc" ]] && . "$RCFILE"
EOF
}

while [ "$#" -gt 0 ]
do
	install_user "$1"
	shift
done
